### ISSUE TITLE
Security exception while installing example (because of adroid:exported)

### ISSUE THREAD

**Issue by qespr** [daadu/receive_intent#30]
Example app crashes and fails to properly install

**To Reproduce**
1) Download example
2) Try to run example
3) It won't run the example nor adb command works

**Expected behavior**
The example runs

**Smartphone:**
 - Device: Xiaomy Redmi Note 5
 - OS:  Android 11 (LineageOS)

FIX: change [this](https://github.com/daadu/receive_intent/blob/f7d1f3571270d009d0edd10afe03517dbeba4f3a/example/android/app/src/main/AndroidManifest.xml#L8) to ``true``, then it works

I can make a pull  request if you want me to.

Thanks for the package btw, looks like very good so far.

Stack trace probably not necessary:
```
ProcessException: Process exited abnormally with exit code 255:
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000
cmp=com.bhikadia.receive_intent_example/.MainActivity (has extras) }


Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER]
flg=0x30000000 cmp=com.bhikadia.receive_intent_example/.MainActivity (has extras) } from null (pid=25985, uid=2000) not exported from uid 10320
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1043)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:999)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:669)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1105)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1077)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3670)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:544)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:186)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10514)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5053)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2875)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
  Command: /home/michal/Android/Sdk/platform-tools/adb -s 67524246 shell am start -a android.intent.action.MAIN -c
  android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
  com.bhikadia.receive_intent_example/com.bhikadia.receive_intent_example.MainActivity
```

**Comment by qespr** [comment]
nvm I'm blind theres already PR for this
